# SPDX-License-Identifier: BSD-3-Clause
# Copyright Contributors to the OpenColorIO Project.

# travis-ci.org build file
# https://docs.travis-ci.com/user/languages/cpp

branches:
  only:
    - master
    - /^RB-.*$/

matrix:
  include:
    # Linux jobs
    - name: linux_clang_sonar
      if: branch = ci_test
      os: linux
      dist: trusty
      language: cpp
      compiler: clang
      addons:
        sonarcloud:
          organization: imageworks
          token: $SONAR_TOKEN

# Install missing packages
before_install:
  # Linux ones
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update -qq;
      sudo apt-get install -y -qq freeglut3-dev libglew-dev libxmu-dev libxi-dev;
      mkdir ${TRAVIS_BUILD_DIR}/_cmake;
      wget https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.sh;
      sh cmake-3.12.2-Linux-x86_64.sh -- --skip-license --prefix=${TRAVIS_BUILD_DIR}/_cmake;
      export PATH="${TRAVIS_BUILD_DIR}/_cmake/bin:$PATH";
    fi

install:
  - git fetch --unshallow --no-tags https://github.com/imageworks/OpenColorIO.git +refs/heads/master:refs/remotes/origin/master

# Run the Build script
script:
  - cmake -DCMAKE_INSTALL_PREFIX=_install -DCMAKE_BUILD_TYPE=Debug -DOCIO_BUILD_TESTS=OFF -DOCIO_BUILD_GPU_TESTS=OFF -DOCIO_BUILD_DOCS=OFF .
  - build-wrapper-linux-x86-64 --out-dir bw_output make clean all
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

