# SPDX-License-Identifier: BSD-3-Clause
# Copyright Contributors to the OpenColorIO Project.

# azure-pipelines build file
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema

jobs:

# - job: Linux
#   strategy:
#     matrix:
#       Ubuntu 18.04 GCC 6:
#         agentImage: 'ubuntu-16.04'
#         containerImage: michdolan/opencolorio:ubuntu18_gcc6
#   pool:
#     vmImage: $(agentImage)
#   container: $[ variables['containerImage'] ]

#   steps:

#   - template: share/azure/build-steps.yml
#     parameters:
#       cxxFlags: -std=c++14 -fPIC


- job: macOS
  strategy:
    matrix:
      10.14 AppleClang 10.0:
        agentImage: 'macOS-10.14'
  pool:
    vmImage: $(agentImage)
  
  steps:

  - bash: |
      brew update
      brew install glew
      brew install pyenv
      brew upgrade cmake 
      xcode-select --install
    displayName: Install dependencies

  - bash: |
      echo 'eval "$(pyenv init -)"' >> .bash_profile
      source .bash_profile
      export PYTHON_CONFIGURE_OPTS="--enable-framework"
      pyenv install -v 2.7.16
      pyenv global 2.7.16
      export OPTIONS="$OPTIONS \
        -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython2.7.dylib"
      export OPTIONS="$OPTIONS \
        -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python2.7"
      export OPTIONS="$OPTIONS \
        -DPYTHON_EXECUTABLE=$(which python2)"
    displayName: Configure Python

  - bash: |
      echo PYTHON_CONFIGURE_OPTS
      echo OPTIONS
      python --version
    displayName: Test persistent env

  - template: share/azure/build-steps.yml
    parameters:
      cxxFlags: -std=c++14 -fPIC -Wno-deprecated-register


# - job: Windows
#   strategy:
#     matrix:
#       Windows-VC:
#         agentImage: 'vs2017-win2016'
#         cCompiler:
#         cxxCompiler:
#   pool:
#     vmImage: $(agentImage)

trigger:
- ci_test
