# azure-pipelines template file
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

parameters:
  buildType: Release
  cmakeOpts: ''

steps:
- bash: |
    cmake --build . \
          --target install \
          --config ${{ parameters.buildType }} \
          ${{ parameters.cmakeOpts }}
  workingDirectory: _build
  displayName: Build OCIO

- template: test.yml
